// apps/playground/src/App.tsx
import React from "react";
import { VideoPlayerWrapper } from "react-video-player";
import "react-video-player/style.css";

export default function App() {
  return (
    <div style={{ padding: 24 }}>
      <h2>react-video-player playground</h2>

      <div className="min-h-screen bg-neutral-950 p-8">
        <VideoPlayerWrapper
          // src="https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
          src="http://index1.circleftp.net/FILE/Hindi%20Movies/2026/Assi%20%282026%29%201080p%20HDTC%20Hindi%20x264/Assi%20%282026%29%201080p%20HDTC%20Hindi%20x264.mkv"
          poster="https://ik.imagekit.io/ikmedia/blog/ghost/content/images/2024/03/Nextjs-Video-Player.png"
          hoverPlay={true}
          onClose={() => console.log("close")}
          controls
          defaultDevice="desktop"
        />
      </div>
    </div>
  );
}

// playground/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { VueVideoPlayer } from "@glitchlab/vue-video-player";
import "@glitchlab/vue-video-player/style.css";

const visible = ref(true);
</script>

<template>
  <div style="padding: 24px">
    <h2>vue-video-player playground</h2>

    <div class="min-h-screen bg-neutral-950 p-8">
      <VueVideoPlayer
        v-if="visible"
        src="https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        poster="https://ik.imagekit.io/ikmedia/blog/ghost/content/images/2024/03/Nextjs-Video-Player.png"
        :closable="true"
        :controls="true"
        default-device="desktop"
        tooltip-text="Watch the demo"
        @close="visible = false"
      />
    </div>
  </div>
</template>
