// packages/react-video-player/src/HLSPlayer.tsx
"use client";

import Hls from "hls.js";
import React, { useEffect, useImperativeHandle, useRef } from "react";
import type { HLSPlayerProps } from "./types";

export const HLSPlayer = React.forwardRef<HTMLVideoElement, HLSPlayerProps>(
    ({ src, hlsConfig, isHls, children, ...videoProps }, forwardedRef) => {
        const internalRef = useRef<HTMLVideoElement | null>(null);
        const hlsRef = useRef<Hls | null>(null);

        useImperativeHandle(forwardedRef, () => internalRef.current as HTMLVideoElement);

        const canUseHlsJs = globalThis.window !== undefined && Hls.isSupported();
        const shouldUseHls =
            Boolean(isHls) || (canUseHlsJs && typeof src === "string" && src.endsWith(".m3u8"));

        useEffect(() => {
            if (!src) return;
            const videoEl = internalRef.current;
            if (!videoEl) return;

            // destroy previous
            if (hlsRef.current) {
                hlsRef.current.destroy();
                hlsRef.current = null;
            }

            // reset video element
            videoEl.pause();
            videoEl.removeAttribute("src");
            while (videoEl.firstChild) videoEl.firstChild.remove();

            if (shouldUseHls) {
                const hls = new Hls(hlsConfig);
                hlsRef.current = hls;

                hls.attachMedia(videoEl);
                hls.loadSource(src);

                hls.on(Hls.Events.ERROR, (_evt, data) => {
                    if (data.fatal) {
                        hls.destroy();
                        hlsRef.current = null;
                    }
                });
            } else {
                // native playback
                videoEl.src = src;
                videoEl.load();
            }

            return () => {
                if (hlsRef.current) {
                    hlsRef.current.destroy();
                    hlsRef.current = null;
                }
                videoEl.pause();
                videoEl.removeAttribute("src");
                while (videoEl.firstChild) videoEl.firstChild.remove();
                videoEl.load();
            };
        }, [src, shouldUseHls, hlsConfig]);

        // Captions are the consumer's responsibility — pass <track> elements as children.
        // NOSONAR: typescript:S4084
        return (
            <video ref={internalRef} {...videoProps}>
                {children}
            </video>
        );
    }
);

HLSPlayer.displayName = "HLSPlayer";
export default HLSPlayer;

// playground/vue/src/HLSPlayer.vue
<script setup lang="ts">
import Hls from "hls.js";
import { ref, watch, onUnmounted } from "vue";
import type { HlsConfig } from "hls.js";

const props = withDefaults(
  defineProps<{
    src: string;
    hlsConfig?: HlsConfig;
    isHls?: boolean;
    muted?: boolean;
    loop?: boolean;
    controls?: boolean;
    playsInline?: boolean;
    preload?: string;
    poster?: string;
    class?: string;
  }>(),
  {
    muted: true,
    loop: false,
    controls: false,
    playsInline: true,
    preload: "metadata",
  }
);

const emit = defineEmits<{
  play: [];
  pause: [];
}>();

const videoEl = ref<HTMLVideoElement | null>(null);
const hlsInstance = ref<Hls | null>(null);

const canUseHlsJs = typeof window !== "undefined" && Hls.isSupported();
const shouldUseHls = (src: string) =>
  Boolean(props.isHls) || (canUseHlsJs && src.endsWith(".m3u8"));

function cleanup() {
  if (hlsInstance.value) {
    hlsInstance.value.destroy();
    hlsInstance.value = null;
  }
  const el = videoEl.value;
  if (!el) return;
  el.pause();
  el.removeAttribute("src");
  while (el.firstChild) el.removeChild(el.firstChild);
  el.load();
}

function initPlayer(src: string) {
  const el = videoEl.value;
  if (!el || !src) return;

  cleanup();

  if (shouldUseHls(src)) {
    const hls = new Hls(props.hlsConfig);
    hlsInstance.value = hls;
    hls.attachMedia(el);
    hls.loadSource(src);
    hls.on(Hls.Events.ERROR, (_evt, data) => {
      if (data.fatal) {
        hls.destroy();
        hlsInstance.value = null;
      }
    });
  } else {
    el.src = src;
    el.load();
  }
}

watch(
  () => props.src,
  (src) => {
    if (src) initPlayer(src);
  },
  { immediate: true }
);

onUnmounted(cleanup);

// Expose video element for parent
defineExpose({ videoEl });
</script>

<template>
  <video
    ref="videoEl"
    :muted="muted"
    :loop="loop"
    :controls="controls"
    :playsinline="playsInline"
    :preload="preload"
    :poster="poster"
    :class="props.class"
    @play="emit('play')"
    @pause="emit('pause')"
  />
</template>
